/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package menu;

import SQL.Conexion;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author orell
 */
public class IngHotel extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngHotel
     */
    public IngHotel() {
        initComponents();
        llenarComboUbicaciones();
        llenarComboHotel();
        
    }
private void llenarComboUbicaciones() {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        // Obtener la conexión a SQL Server
        Conexion conect = new Conexion();
        con = conect.getConexion();

        // Consulta SQL para obtener los ID_Ubicacion de la tabla UBICACIONES
        String sql = "SELECT ID_Ubicacion FROM UBICACIONES";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        // Limpiar el JComboBox antes de agregar nuevos elementos
        cmbIDubi.removeAllItems();

        // Recorrer los resultados y agregar los ID_Ubicacion al JComboBox
        while (rs.next()) {
            String idUbicacion = rs.getString("ID_Ubicacion");
            cmbIDubi.addItem(idUbicacion); // Agregar cada ID_Ubicacion al combo box
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar las ubicaciones", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}


private void llenarComboHotel() {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        // Obtener la conexión a SQL Server
        Conexion conect = new Conexion();
        con = conect.getConexion();

        // Consulta SQL para obtener los ID_Ubicacion de la tabla UBICACIONES
        String sql = "SELECT ID_Hotel FROM HOTELES";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        // Limpiar el JComboBox antes de agregar nuevos elementos
        cmbidhotel.removeAllItems();

        // Recorrer los resultados y agregar los ID_Ubicacion al JComboBox
        while (rs.next()) {
            String idHotel = rs.getString("ID_Hotel");
            cmbidhotel.addItem(idHotel); // Agregar cada ID_Ubicacion al combo box
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar las hotel", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttotalhabi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id_hotel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbcate = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtnomhotel = new javax.swing.JTextField();
        cmbIDubi = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtidhabitacion = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmbidhotel = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttipo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtcapacidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtprecioxnoche = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(3, 54, 61));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hotel_1.png"))); // NOI18N
        jLabel5.setText("Hoteles ");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel1.setText("ID_Hotel:");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Utilice esta ventana para agregar o modificar");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel3.setText("los hoteles del sistema.");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel6.setText("ID_Ubicación:");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel7.setText("Nombre_hotel:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hotel2 (1).png"))); // NOI18N
        jButton1.setText("Guardar Hotel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hotel2 (1).png"))); // NOI18N
        jButton2.setText("Modificar Hotel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel9.setText("Categoría:");

        cmbcate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estrella 1", "estrella 2", "estrella 3", "estrella 4", "estrella 5" }));
        cmbcate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel14.setText("Total habitaciones:");

        cmbIDubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIDubiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbIDubi, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(id_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtnomhotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbcate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txttotalhabi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbIDubi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbcate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalhabi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel8.setText("ID_Habitacion:");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel10.setText("Utilice esta ventana para agregar o modificar");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel11.setText("las habitaciones disponibles.");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel12.setText("ID_Hotel:");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/habitacion (1).png"))); // NOI18N
        jButton3.setText("Guardar Habitación");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/habitacion (1).png"))); // NOI18N
        jButton4.setText("Modificar Habitación");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmbidhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidhotelActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel13.setText("Capacidad:");

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel15.setText("Tipo_Habitación:");

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel16.setText("Estado:");

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 16)); // NOI18N
        jLabel17.setText("Precio Por Noche:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(44, 44, 44)
                        .addComponent(txtidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(83, 83, 83)
                        .addComponent(cmbidhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(29, 29, 29)
                        .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(97, 97, 97)
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtprecioxnoche, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(68, 68, 68)
                        .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtidhabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbidhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecioxnoche, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Captura de pantalla 2024-10-21 194053_1.png"))); // NOI18N
        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel4.setText("Airtemala™ 2024. Todos los derechos registrados.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    // Validar que ID_Hotel contiene solo números
    if (!id_hotel.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "El campo ID del Hotel debe contener solo números.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que Total_Habitaciones es un número
    if (!txttotalhabi.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "El campo Total de Habitaciones debe contener solo números.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que Nombre_Hotel solo contiene letras y espacios
    if (!txtnomhotel.getText().matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "El campo Nombre del Hotel debe contener solo letras y espacios.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtener la conexión a SQL Server
    Conexion connect = new Conexion();
    Connection con = connect.getConexion();

    // Consulta SQL preparada para actualizar datos
    String sql = "UPDATE HOTELES SET ID_Ubicacion = ?, Nombre_Hotel = ?, Categoria = ?, Total_Habitaciones = ? WHERE ID_Hotel = ?";
    PreparedStatement pst = con.prepareStatement(sql);

    // Asignar los valores de los campos
    pst.setInt(1, Integer.parseInt(cmbIDubi.getSelectedItem().toString()));
    pst.setString(2, txtnomhotel.getText());

    // Extraer el número de estrellas de la categoría y validar que es un número
    String categoria = cmbcate.getSelectedItem().toString();
    int estrellas;
    try {
        estrellas = Integer.parseInt(categoria.replaceAll("[^0-9]", "")); // Remueve todo excepto los números
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La categoría debe contener un número de estrellas.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    pst.setInt(3, estrellas);

    // Total de habitaciones como número
    pst.setInt(4, Integer.parseInt(txttotalhabi.getText()));

    // ID_Hotel como condición para identificar el registro
    pst.setString(5, id_hotel.getText());

    // Ejecutar la consulta de actualización
    int n = pst.executeUpdate();

    // Verificar si se modificaron los datos
    if (n > 0) {
        JOptionPane.showMessageDialog(this, "DATOS MODIFICADOS CORRECTAMENTE");
    }

    // Limpiar los campos
    id_hotel.setText("");
    cmbIDubi.setSelectedIndex(0);
    txtnomhotel.setText("");
    cmbcate.setSelectedIndex(0);
    txttotalhabi.setText("");

} catch (SQLException | HeadlessException e) {
    JOptionPane.showMessageDialog(this, "LOS DATOS NO SE MODIFICARON CORRECTAMENTE", "Error", JOptionPane.ERROR_MESSAGE);
    System.out.println("Error: " + e.getMessage());
}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {
    // Obtener la conexión a SQL Server
    Conexion connect = new Conexion();
    Connection con = connect.getConexion();

    // Consulta SQL preparada para actualizar datos
    String sql = "UPDATE HOTELES SET ID_Ubicacion = ?, Nombre_Hotel = ?, Categoria = ?, Total_Habitaciones = ? WHERE ID_Hotel = ?";
    PreparedStatement pst = con.prepareStatement(sql);

    // Asignar los valores de los campos
    pst.setInt(1, Integer.parseInt((String) cmbIDubi.getSelectedItem()));
    pst.setString(2, txtnomhotel.getText());
    pst.setInt(3, Integer.parseInt((String) cmbcate.getSelectedItem()));
    pst.setString(4, txttotalhabi.getText());
    pst.setString(5, id_hotel.getText()); // ID_Hotel como condición para identificar el registro

    // Ejecutar la consulta de actualización
    int n = pst.executeUpdate();

    // Verificar si se modificaron los datos
    if (n > 0) {
        JOptionPane.showMessageDialog(this, "DATOS MODIFICADOS CORRECTAMENTE");
    }

    // Limpiar los campos
    id_hotel.setText("");
    cmbIDubi.setSelectedIndex(0);
    txtnomhotel.setText("");
    cmbcate.setSelectedIndex(0);
    txttotalhabi.setText("");

} catch (SQLException | HeadlessException e) {
    JOptionPane.showMessageDialog(this, "LOS DATOS NO SE MODIFICARON CORRECTAMENTE", "Error", JOptionPane.ERROR_MESSAGE);
    System.out.println("Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try {
    // Obtener la conexión a SQL Server
    Conexion connect = new Conexion();
    Connection con = connect.getConexion();

    // Consulta SQL preparada con parámetros
    String sql = "INSERT INTO HABITACIONES (ID_Habitacion, ID_Hotel, Tipo_Habi, Estado, Capacidad, Precio_Noche) VALUES (?, ?, ?, ?, ?, ?)";
    PreparedStatement pst = con.prepareStatement(sql);

    // Asignar los valores de los campos
    pst.setString(1, txtidhabitacion.getText());
    pst.setInt(2, Integer.parseInt(cmbidhotel.getSelectedItem().toString()));  // Convierte correctamente el valor de JComboBox a int
    pst.setString(3, txttipo.getText());
    pst.setString(4, txtestado.getText());  // Agregado para el campo Estado

    // Asegúrate de que Capacidad y Precio por Noche sean numéricos
    pst.setInt(5, Integer.parseInt(txtcapacidad.getText()));  // Cambiado a setInt si es un número
    pst.setDouble(6, Double.parseDouble(txtprecioxnoche.getText()));  // Cambiado a setDouble si es un valor decimal

    // Ejecutar la consulta
    int n = pst.executeUpdate();

    // Verificar si se insertaron los datos
    if (n > 0) {
        JOptionPane.showMessageDialog(this, "DATOS GUARDADOS CORRECTAMENTE");
    }

    // Limpiar los campos
    txtidhabitacion.setText("");
    cmbidhotel.setSelectedIndex(0);
    txttipo.setText("");
    txtestado.setText("");
    txtcapacidad.setText("");
    txtprecioxnoche.setText("");

} catch (SQLException | HeadlessException | NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "LOS DATOS NO SE GUARDARON CORRECTAMENTE", "Error", JOptionPane.ERROR_MESSAGE);
    System.out.println("Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try {
    // Obtener la conexión a SQL Server
    Conexion connect = new Conexion();
    Connection con = connect.getConexion();

    // Consulta SQL preparada para actualizar datos
    String sql = "UPDATE HOTELES SET ID_Hotel = ?, Tipo_Habi = ?, Estado = ?, Capacidad = ?, Precio_Noche = ? WHERE ID_Habitacion = ?";
    PreparedStatement pst = con.prepareStatement(sql);

    // Asignar los valores de los campos
    pst.setInt(1, Integer.parseInt((String) cmbidhotel.getSelectedItem()));
    pst.setString(2, txttipo.getText());
    pst.setString(3, txtestado.getText());
    pst.setString(4, txtcapacidad.getText());
    pst.setString(5, txtprecioxnoche.getText());
    pst.setString(6, txtidhabitacion.getText()); // ID_Habitacion como condición para identificar el registro

    // Ejecutar la consulta de actualización
    int n = pst.executeUpdate();

    // Verificar si se modificaron los datos
    if (n > 0) {
        JOptionPane.showMessageDialog(this, "DATOS MODIFICADOS CORRECTAMENTE");
    }

    // Limpiar los campos
    txtidhabitacion.setText("");
    cmbidhotel.setSelectedIndex(0);
    txttipo.setText("");
    txtestado.setText("");
    txtcapacidad.setText("");
    txtprecioxnoche.setText("");

} catch (SQLException | HeadlessException e) {
    JOptionPane.showMessageDialog(this, "LOS DATOS NO SE MODIFICARON CORRECTAMENTE", "Error", JOptionPane.ERROR_MESSAGE);
    System.out.println("Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbcateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcateActionPerformed

    private void cmbidhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidhotelActionPerformed
String selectedID = (String) cmbidhotel.getSelectedItem();
    }//GEN-LAST:event_cmbidhotelActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
             try {
        // Obtiene el InternalFrame que quieres cerrar
        this.dispose();  // Cierra el InternalFrame actual
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    // Llama al método hacerBotonesVisibles en la clase del menú
    Menu menu = (Menu) SwingUtilities.getAncestorOfClass(Menu.class, this);
    if (menu != null) {
        menu.hacerBotonesVisibles();
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cmbIDubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIDubiActionPerformed
         String selectedID2 = (String) cmbIDubi.getSelectedItem();
    }//GEN-LAST:event_cmbIDubiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbIDubi;
    private javax.swing.JComboBox<String> cmbcate;
    private javax.swing.JComboBox<String> cmbidhotel;
    private javax.swing.JTextField id_hotel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtidhabitacion;
    private javax.swing.JTextField txtnomhotel;
    private javax.swing.JTextField txtprecioxnoche;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txttotalhabi;
    // End of variables declaration//GEN-END:variables
}
