/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import SQL.Conexion;
import java.awt.Color;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author orell
 */
public class Menu extends javax.swing.JFrame {

   

    public void setBotonColorVerde() {
        jButton1.setBackground(Color.GREEN);
    }
    public Menu() {
        initComponents();
        jButtonTransportes.setVisible(false);
        jButtonDestinos.setVisible(false);
        jButtonClientes.setVisible(false);
        jButtonHoteles.setVisible(false);
        jButtonRestaurantes.setVisible(false);
        jButtonReservaciones.setVisible(false);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel5.setVisible(false);
        jLabel4.setVisible(false);
        jLabel7.setVisible(false);
        jLabel3.setVisible(false);
        jLabel8.setVisible(false);
        jLabel1.setVisible(false);
    }
    
    // Método para hacer visibles los botones
    public void hacerBotonesVisibles() {
        jButtonTransportes.setVisible(true);
        jButtonDestinos.setVisible(true);
        jButtonClientes.setVisible(true);
        jButtonHoteles.setVisible(true);
        jButtonRestaurantes.setVisible(true);
        jButtonReservaciones.setVisible(true);
        jLabel2.setVisible(true);
        jLabel6.setVisible(true);
        jLabel5.setVisible(true);
        jLabel4.setVisible(true);
        jLabel7.setVisible(true);
        jLabel3.setVisible(true);
        jLabel8.setVisible(true);
        jLabel1.setVisible(true);
    }
    
    public void hacerBotonesinVisibles() {
        jButtonTransportes.setVisible(false);
        jButtonDestinos.setVisible(false);
        jButtonClientes.setVisible(false);
        jButtonHoteles.setVisible(false);
        jButtonRestaurantes.setVisible(false);
        jButtonReservaciones.setVisible(false);
        jLabel2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel5.setVisible(false);
        jLabel4.setVisible(false);
        jLabel7.setVisible(false);
        jLabel3.setVisible(false);
        jLabel8.setVisible(false);
        jLabel1.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jButtonDestinos = new javax.swing.JButton();
        jButtonTransportes = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonHoteles = new javax.swing.JButton();
        jButtonRestaurantes = new javax.swing.JButton();
        jButtonReservaciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jButtonDestinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/destino.png"))); // NOI18N
        jButtonDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDestinosActionPerformed(evt);
            }
        });

        jButtonTransportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/transporte.png"))); // NOI18N
        jButtonTransportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransportesActionPerformed(evt);
            }
        });

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente.png"))); // NOI18N
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonHoteles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hotel.png"))); // NOI18N
        jButtonHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHotelesActionPerformed(evt);
            }
        });

        jButtonRestaurantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/restaurante.png"))); // NOI18N
        jButtonRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurantesActionPerformed(evt);
            }
        });

        jButtonReservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reserva.png"))); // NOI18N
        jButtonReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservacionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Airtemala™ 2024. Todos los derechos registrados.");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel2.setText("Bienvenido(a). Inicia sesión y selecciona una de las opciones:");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel3.setText("Reservaciones Y Consultas");

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel4.setText("Hoteles");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel5.setText("Transporte");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel6.setText("Destinos");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel7.setText("Restaurantes");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel8.setText("Clientes");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(315, 315, 315)
                .addComponent(jLabel4)
                .addGap(176, 176, 176))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDestinos)
                            .addComponent(jButtonRestaurantes)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7)))
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTransportes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonClientes))
                        .addGap(254, 254, 254)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReservaciones))
                        .addGap(139, 139, 139))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRestaurantes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonTransportes)
                            .addComponent(jButtonHoteles)
                            .addComponent(jButtonDestinos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonClientes)
                            .addComponent(jButtonReservaciones))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        jPanel1.setBackground(new java.awt.Color(3, 54, 61));

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Captura de pantalla 2024-10-21 194305.png"))); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Captura de pantalla 2024-10-21 194053_1.png"))); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Diseño sin título.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public class UsuarioSesion {

    // Variable estática para guardar el usuario activo
    private static String usuarioActivo = null;

    // Método para establecer el usuario al iniciar sesión
    public static void setUsuarioActivo(String usuario) {
        usuarioActivo = usuario;
    }

    // Método para obtener el usuario activo
    public static String getUsuarioActivo() {
        return usuarioActivo;
    }

    // Método para cerrar la sesión
    public static void cerrarSesion() {
        usuarioActivo = null; // Limpiar la sesión
    }

    // Método para verificar si hay una sesión activa
    public static boolean isSesionActiva() {
        return usuarioActivo != null;
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Verificamos si hay un usuario activo
if (UsuarioSesion.getUsuarioActivo() != null) {
    // Ya hay una sesión activa, podrías mostrar un mensaje o hacer otra acción
    JOptionPane.showMessageDialog(null, "Ya hay una sesión activa: " + UsuarioSesion.getUsuarioActivo());
} else {
    // Deshabilitar el PanelPrincipal
    PanelPrincipal.setEnabled(false);

    // No hay sesión iniciada, mostrar el JInternalFrame de inicio de sesión
    InicioSesion obj = new InicioSesion();
    PanelPrincipal.add(obj);
    obj.toFront(); // Asegurarse de que el frame se muestre al frente
    obj.setLocation(PanelPrincipal.getWidth() / 2 - obj.getWidth() / 2, PanelPrincipal.getHeight() / 2 - obj.getHeight() / 2);
   
    try {
        obj.setMaximum(true); 
        obj.setSelected(true); // Asegurarse de que el JInternalFrame tenga el foco
    } catch (PropertyVetoException ex) {
        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
    }

    obj.setVisible(true);

    // Evento que reacciona cuando el frame de inicio de sesión se cierra
    obj.addInternalFrameListener(new InternalFrameAdapter() {
        @Override
        public void internalFrameClosed(InternalFrameEvent e) {
            PanelPrincipal.setEnabled(true); // Habilitar el PanelPrincipal nuevamente después de cerrar el frame
        }
    });
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
    
    // Si el usuario elige cerrar sesión
    if (respuesta == JOptionPane.YES_OPTION) {
        UsuarioSesion.setUsuarioActivo(null);  // Limpiar el usuario activo
        jButton1.setBackground(null); // Cambiar el color del botón de inicio de sesión a su estado original
        JOptionPane.showMessageDialog(null, "Sesión cerrada.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonTransportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransportesActionPerformed
                // Crear el JInternalFrame
        IngTransporte IngTransporte = new IngTransporte();
    jButtonDestinos.setVisible(false);
    jButtonTransportes.setVisible(false);
    jButtonHoteles.setVisible(false);
    jButtonRestaurantes.setVisible(false);
    jButtonReservaciones.setVisible(false);
    jButtonClientes.setVisible(false);
    
    jLabel2.setVisible(false);
    jLabel6.setVisible(false);
    jLabel5.setVisible(false);
    jLabel4.setVisible(false);
    jLabel7.setVisible(false);
    jLabel3.setVisible(false);
    jLabel8.setVisible(false);
    jLabel1.setVisible(false);  
        
        IngTransporte.setLocation(PanelPrincipal.getWidth() / 2 - IngTransporte.getWidth() / 2, 
        PanelPrincipal.getHeight() / 2 - IngTransporte.getHeight() / 2);
    
        // Agregar el JInternalFrame al PanelPrincipal
        PanelPrincipal.add(IngTransporte);
    
        // Mostrar el JInternalFrame
        IngTransporte.setVisible(true);

        // Asegurarse de que se muestre al frente
        IngTransporte.toFront(); 
        try {
            IngTransporte.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTransportesActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
       IngClientes IngClientes = new IngClientes();
    
    jButtonDestinos.setVisible(false);
    jButtonTransportes.setVisible(false);
    jButtonHoteles.setVisible(false);
    jButtonRestaurantes.setVisible(false);
    jButtonReservaciones.setVisible(false);
    jButtonClientes.setVisible(false);
    
    jLabel2.setVisible(false);
    jLabel6.setVisible(false);
    jLabel5.setVisible(false);
    jLabel4.setVisible(false);
    jLabel7.setVisible(false);
    jLabel3.setVisible(false);
    jLabel8.setVisible(false);
    jLabel1.setVisible(false);  
        
        IngClientes.setLocation(PanelPrincipal.getWidth() / 2 - IngClientes.getWidth() / 2, 
        PanelPrincipal.getHeight() / 2 - IngClientes.getHeight() / 2);
    
        // Agregar el JInternalFrame al PanelPrincipal
        PanelPrincipal.add(IngClientes);
    
        // Mostrar el JInternalFrame
        IngClientes.setVisible(true);

        // Asegurarse de que se muestre al frente
        IngClientes.toFront(); 
        try {
            IngClientes.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHotelesActionPerformed
        IngHotel IngHotel = new IngHotel();
    
     jButtonDestinos.setVisible(false);
    jButtonTransportes.setVisible(false);
    jButtonHoteles.setVisible(false);
    jButtonRestaurantes.setVisible(false);
    jButtonReservaciones.setVisible(false);
    jButtonClientes.setVisible(false);
    
    jLabel2.setVisible(false);
    jLabel6.setVisible(false);
    jLabel5.setVisible(false);
    jLabel4.setVisible(false);
    jLabel7.setVisible(false);
    jLabel3.setVisible(false);
    jLabel8.setVisible(false);   // Configurar tamaño y ubicación del JInternalFrame
    jLabel1.setVisible(false);     
        IngHotel.setLocation(PanelPrincipal.getWidth() / 2 - IngHotel.getWidth() / 2, 
        PanelPrincipal.getHeight() / 2 - IngHotel.getHeight() / 2);
    
        // Agregar el JInternalFrame al PanelPrincipal
        PanelPrincipal.add(IngHotel);
    
        // Mostrar el JInternalFrame
        IngHotel.setVisible(true);

        // Asegurarse de que se muestre al frente
        IngHotel.toFront(); 
        try {
            IngHotel.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonHotelesActionPerformed

    private void jButtonRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurantesActionPerformed
        IngRestaurantes IngRestaurantes = new IngRestaurantes();
    
       jButtonDestinos.setVisible(false);
    jButtonTransportes.setVisible(false);
    jButtonHoteles.setVisible(false);
    jButtonRestaurantes.setVisible(false);
    jButtonReservaciones.setVisible(false);
    jButtonClientes.setVisible(false);
    
    jLabel2.setVisible(false);
    jLabel6.setVisible(false);
    jLabel5.setVisible(false);
    jLabel4.setVisible(false);
    jLabel7.setVisible(false);
    jLabel3.setVisible(false);
    jLabel8.setVisible(false);
    jLabel1.setVisible(false);      
        IngRestaurantes.setLocation(PanelPrincipal.getWidth() / 2 - IngRestaurantes.getWidth() / 2, 
        PanelPrincipal.getHeight() / 2 - IngRestaurantes.getHeight() / 2);
    
        // Agregar el JInternalFrame al PanelPrincipal
        PanelPrincipal.add(IngRestaurantes);
    
        // Mostrar el JInternalFrame
        IngRestaurantes.setVisible(true);

        // Asegurarse de que se muestre al frente
        IngRestaurantes.toFront(); 
        try {
            IngRestaurantes.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonRestaurantesActionPerformed

    private void jButtonReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservacionesActionPerformed
       IngReservaciones IngReservaciones = new IngReservaciones();
    
        jButtonDestinos.setVisible(false);
    jButtonTransportes.setVisible(false);
    jButtonHoteles.setVisible(false);
    jButtonRestaurantes.setVisible(false);
    jButtonReservaciones.setVisible(false);
    jButtonClientes.setVisible(false);
    jPanel1.setVisible(false);
    jLabel2.setVisible(false);
    jLabel6.setVisible(false);
    jLabel5.setVisible(false);
    jLabel4.setVisible(false);
    jLabel7.setVisible(false);
    jLabel3.setVisible(false);
    jLabel8.setVisible(false);
    jLabel1.setVisible(false);  
        IngReservaciones.setLocation(PanelPrincipal.getWidth() / 2 - IngReservaciones.getWidth() / 2, 
        PanelPrincipal.getHeight() / 2 - IngReservaciones.getHeight() / 2);
    
        // Agregar el JInternalFrame al PanelPrincipal
        PanelPrincipal.add(IngReservaciones);
    
        // Mostrar el JInternalFrame
        IngReservaciones.setVisible(true);

        // Asegurarse de que se muestre al frente
        IngReservaciones.toFront(); 
        try {
            IngReservaciones.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonReservacionesActionPerformed

    private void jButtonDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDestinosActionPerformed
        // Crear el JInternalFrame
        IngDestinos IngDestinos = new IngDestinos();
    
        jButtonDestinos.setVisible(false);
    jButtonTransportes.setVisible(false);
    jButtonHoteles.setVisible(false);
    jButtonRestaurantes.setVisible(false);
    jButtonReservaciones.setVisible(false);
    jButtonClientes.setVisible(false);
    
    jLabel2.setVisible(false);
    jLabel6.setVisible(false);
    jLabel5.setVisible(false);
    jLabel4.setVisible(false);
    jLabel7.setVisible(false);
    jLabel3.setVisible(false);
    jLabel8.setVisible(false);
    jLabel1.setVisible(false);  
        IngDestinos.setLocation(PanelPrincipal.getWidth() / 2 - IngDestinos.getWidth() / 2, 
        PanelPrincipal.getHeight() / 2 - IngDestinos.getHeight() / 2);
    
        // Agregar el JInternalFrame al PanelPrincipal
        PanelPrincipal.add(IngDestinos);
    
        // Mostrar el JInternalFrame
        IngDestinos.setVisible(true);

        // Asegurarse de que se muestre al frente
        IngDestinos.toFront(); 
        try {
            IngDestinos.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDestinosActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonDestinos;
    private javax.swing.JButton jButtonHoteles;
    private javax.swing.JButton jButtonReservaciones;
    private javax.swing.JButton jButtonRestaurantes;
    private javax.swing.JButton jButtonTransportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
